# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Debug Database Connection
        run: |
          echo "DATABASE_URL starts with: ${DATABASE_URL:0:20}..."
          echo "DATABASE_USERNAME starts with: ${DATABASE_USERNAME:0:10}..."
    
      - name: Enviroment Variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "CORREO=${{ secrets.CORREO }}" >> $GITHUB_ENV
          echo "CORREO_PASSWORD=${{ secrets.CORREO_PASSWORD }}" >> $GITHUB_ENV
      - name: Build With Maven
        run: mvn -B package --file pom.xml
        #run: mvn -B package --file pom.xml -Dspring.datasource.url=${{ secrets.DATABASE_URL }} -Dspring.datasource.username=${{ secrets.DATABASE_USERNAME }} -Dspring.datasource.password=${{ secrets.DATABASE_PASSWORD }}
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
            name: SpringBoot Report               # Name of the folder
            path: target/site/jacoco/
